controller_manager:
  ros__parameters:
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_position_controller:
      type: position_controllers/JointGroupPositionController

arm_position_controller:
  ros__parameters:
    joints:
      - Shoulder_Pitch
      - Elbow
    interface_name: position
